name: Web Crawler

on:
  schedule:
    - cron: "*/5 * * * *"  # Exécute toutes les 5 minutes
  workflow_dispatch:  # Permet aussi de lancer manuellement

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ajoute tes dépendances ici

      - name: Run Web Crawler
        run: python main.py  # Exécute ton script Python

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add articles.db
          git commit -m "Mise à jour des articles récupérés" || echo "Aucune mise à jour"
          git push
